/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Model.ConnectionFactory;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author é o r's
 */
public class AddLixo extends javax.swing.JFrame {

    /**
     * Creates new form AddLixo
     */
    public AddLixo() {
        super("ADICIONAR LIXO");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdLixo = new javax.swing.JTextField();
        cboLixo = new javax.swing.JComboBox<>();
        txtNomeLixo = new javax.swing.JTextField();
        txtCaminhoImg = new javax.swing.JTextField();
        lblImagem = new javax.swing.JLabel();
        btnAdicionarLixo = new javax.swing.JButton();
        btnAlterarLixo = new javax.swing.JButton();
        btnExcluirLixo = new javax.swing.JButton();
        btnCarregarFoto = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        txtIdLixo.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));
        txtIdLixo.setEnabled(false);

        cboLixo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o tipo do lixo", "Papel", "Vidro", "Metal", "Plástico", "Orgânico" }));

        txtNomeLixo.setBorder(javax.swing.BorderFactory.createTitledBorder("LIXO"));

        txtCaminhoImg.setBorder(javax.swing.BorderFactory.createTitledBorder("CAMINHO DA IMAGEM"));

        btnAdicionarLixo.setBackground(new java.awt.Color(0, 106, 67));
        btnAdicionarLixo.setForeground(new java.awt.Color(255, 255, 255));
        btnAdicionarLixo.setText("Adicionar Lixo");
        btnAdicionarLixo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdicionarLixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarLixoActionPerformed(evt);
            }
        });

        btnAlterarLixo.setBackground(new java.awt.Color(0, 106, 67));
        btnAlterarLixo.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterarLixo.setText("Alterar Lixo");
        btnAlterarLixo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterarLixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarLixoActionPerformed(evt);
            }
        });

        btnExcluirLixo.setBackground(new java.awt.Color(0, 106, 67));
        btnExcluirLixo.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirLixo.setText("Excluir lixo");
        btnExcluirLixo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluirLixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirLixoActionPerformed(evt);
            }
        });

        btnCarregarFoto.setBackground(new java.awt.Color(0, 106, 67));
        btnCarregarFoto.setForeground(new java.awt.Color(255, 255, 255));
        btnCarregarFoto.setText("Carregar Foto");
        btnCarregarFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCarregarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarFotoActionPerformed(evt);
            }
        });

        btnPesquisar.setBackground(new java.awt.Color(0, 106, 67));
        btnPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\é o r's\\Desktop\\leftarrow1_80827.png")); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNomeLixo, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(txtIdLixo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboLixo, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCaminhoImg)
                                .addGap(81, 81, 81)))
                        .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAdicionarLixo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnAlterarLixo, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnExcluirLixo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(btnCarregarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(110, 110, 110))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomeLixo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdLixo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboLixo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCaminhoImg, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarLixo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterarLixo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirLixo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarregarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarLixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarLixoActionPerformed
        // TODO add your handling code here:
        adicionarLixo();
    }//GEN-LAST:event_btnAdicionarLixoActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        pesquisarLixo();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnCarregarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarFotoActionPerformed
        // TODO add your handling code here:
        carregarFoto();
    }//GEN-LAST:event_btnCarregarFotoActionPerformed

    private void btnExcluirLixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirLixoActionPerformed
        // TODO add your handling code here:
        excluirLixo();
    }//GEN-LAST:event_btnExcluirLixoActionPerformed

    private void btnAlterarLixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarLixoActionPerformed
        // TODO add your handling code here:
        alterarLixo();
    }//GEN-LAST:event_btnAlterarLixoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddLixo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddLixo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddLixo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddLixo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddLixo().setVisible(true);
            }
        });
    }
    
    ConnectionFactory cf = new ConnectionFactory();
    private FileInputStream fis;
    private File icon;
    private int tamanho;
    private BufferedImage bfi;
    
    private void pesquisarLixo() {
        if (txtNomeLixo.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Digite o nome do lixo");
                txtNomeLixo.requestFocus();
        } else {
            String read = "select * from tb_lixo where nomeLixo = ?";
            try {
                Connection con = cf.conectar();
                PreparedStatement pst = con.prepareStatement(read);
                pst.setString(1, txtNomeLixo.getText());
                ResultSet rs = pst.executeQuery();
                limparCampos();
                if (rs.next()) {
                    txtIdLixo.setText(rs.getString("id"));
                    cboLixo.setSelectedItem(rs.getString("tipoLixo"));
                    txtCaminhoImg.setText(rs.getString("caminhoImg"));
                    File imgsave = new File(rs.getString("caminhoImg"));
                    tamanho = (int)  imgsave.length();
                    Image foto = ImageIO.read(imgsave).getScaledInstance(lblImagem.getWidth(), lblImagem.getHeight(),Image.SCALE_SMOOTH);
                    lblImagem.setIcon(new ImageIcon(foto));
                    lblImagem.updateUI();
                    btnCarregarFoto.setEnabled(true);
                    btnAlterarLixo.setEnabled(true);
                    btnExcluirLixo.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Lixo não cadastrado");
                    limparCampos();
                    btnAdicionarLixo.setEnabled(true);
                    btnCarregarFoto.setEnabled(true); 
                }
                con.close();
            } catch (Exception e) {
                    System.out.println(e);
            }
        }
    }
    
    private void adicionarLixo() {
        if (cboLixo.getSelectedItem().equals("Selecione o tipo do lixo")) {
            JOptionPane.showMessageDialog(null, "Informe o tipo de lixo");
            cboLixo.requestFocus();
        } else if (txtNomeLixo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o nome do lixo");
            txtNomeLixo.requestFocus();
        }else if (txtCaminhoImg.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o caminho da imagem do lixo");
            txtCaminhoImg.requestFocus();
        }else {
            String create = "insert into tb_lixo(nomeLixo, tipolixo, caminhoimg) values (?,?,?)";
            try {
                bfi = ImageIO.read(icon);
                URL url = getClass().getResource("../");
                String pathIcon = url.getPath().substring(1) + "img/" + icon.getName();
                File imgsave = new File(pathIcon);
                ImageIO.write(bfi, "png" , imgsave);
                Connection con = cf.conectar();
                PreparedStatement pst = con.prepareStatement(create);
                pst.setString(1, txtNomeLixo.getText());
                pst.setString(2, cboLixo.getSelectedItem().toString());
                pst.setString(3, txtCaminhoImg.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Lixo adicionado com sucesso");
                limparCampos();
                txtIdLixo.setText(null);
                txtNomeLixo.setText(null);
                con.close();
            } catch (Exception e) {
                    e.printStackTrace();
            }
        }
    }
     
    private void alterarLixo() {
		
        if (txtNomeLixo.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Informe o nome do lixo");
                txtNomeLixo.requestFocus();
        } else if (cboLixo.getSelectedItem().equals("Selecione o tipo do lixo")) {
                JOptionPane.showMessageDialog(null, "Informe o tipo do lixo");
                cboLixo.requestFocus();
        } else if (txtCaminhoImg.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Informe o caminho da imagem do lixo");
                txtCaminhoImg.requestFocus();
        } else {
            String update = "update tb_lixo set nomeLixo=?, tipoLixo=?, caminhoImg=? where idLixo=?";
            try {
                Connection con = cf.conectar();
                PreparedStatement pst = con.prepareStatement(update);
                pst.setString(1, txtNomeLixo.getText());
                pst.setString(2, cboLixo.getSelectedItem().toString());
                pst.setString(3, txtCaminhoImg.getText());
                pst.setString(4, txtIdLixo.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Lixo alterado com sucesso");
                limparCampos();
                txtIdLixo.setText(null);
                txtNomeLixo.setText(null);
                con.close();
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }
    
    private void excluirLixo() {
        if (txtIdLixo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o Id do lixo");
            txtIdLixo.requestFocus();
        } else{
                int confirma = JOptionPane.showConfirmDialog(null, "Confirma a exclusão do lixo", "Atenção!", JOptionPane.YES_NO_OPTION);
                if (confirma == JOptionPane.YES_OPTION) {
                        String delete = "delete from tb_lixo where id=?";
                try {
                    Connection con = cf.conectar();
                    PreparedStatement pst = con.prepareStatement(delete);
                    pst.setString(1, txtIdLixo.getText());
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Lixo excluido com sucesso");
                    limparCampos();
                    txtIdLixo.setText(null);
                    txtNomeLixo.setText(null);
                    con.close();
                } catch (Exception e) {
                    System.out.println(e);
                }
            }
        }
    }
     
    private void carregarFoto(){
            JFileChooser jfc = new JFileChooser();
            jfc.setDialogTitle("Selecionar arquivo");
            jfc.setFileFilter(new FileNameExtensionFilter("Arquivo de imagens(*.PNG,*.JPG,*.JPEG)","png","jpg","jpeg"));
            int resultado = jfc.showOpenDialog(this);
            if(resultado == JFileChooser.APPROVE_OPTION);
            try{
                icon = jfc.getSelectedFile();
                URL url = getClass().getResource("../");
                String path = url.getPath().substring(1) + "img/";
                File directory = new File(path);
      
                if (!directory.exists()){
                    directory.mkdir();
                }
                String pathIcon = path + icon.getName();
                txtCaminhoImg.setText(pathIcon);
                tamanho = (int) jfc.getSelectedFile().length();
                Image foto = ImageIO.read(jfc.getSelectedFile()).getScaledInstance(lblImagem.getWidth(), lblImagem.getHeight(),Image.SCALE_SMOOTH);
                lblImagem.setIcon(new ImageIcon(foto));
                lblImagem.updateUI();
            }catch (Exception e){
                e.printStackTrace();
        }
    }
    
    private void limparCampos() {
        cboLixo.setSelectedItem(null);
        cboLixo.setSelectedItem("Selecione o tipo da lixeira");
        txtCaminhoImg.setText(null);
        lblImagem.setIcon(null);
        btnCarregarFoto.setEnabled(false);
        btnAdicionarLixo.setEnabled(false);
        btnAlterarLixo.setEnabled(false);
        btnExcluirLixo.setEnabled(false);	
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarLixo;
    private javax.swing.JButton btnAlterarLixo;
    private javax.swing.JButton btnCarregarFoto;
    private javax.swing.JButton btnExcluirLixo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JComboBox<String> cboLixo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JTextField txtCaminhoImg;
    private javax.swing.JTextField txtIdLixo;
    private javax.swing.JTextField txtNomeLixo;
    // End of variables declaration//GEN-END:variables
}
