/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Model.ConnectionFactory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLIntegrityConstraintViolationException;
import javax.swing.JOptionPane;

/**
 *
 * @author Miranda
 */
public class ConfiguracoesTela extends javax.swing.JFrame {
    
    static String perfil;
    static int id;

    /**
     * Creates new form ConfiguracoesUsuario
     */
    public ConfiguracoesTela(String perfil, int id) {
        super("PERFIL");
        initComponents();
        txtSenhaUsuario.setEnabled(false);
        this.setLocationRelativeTo(null);
        this.perfil = perfil;
        this.id = id;
        if(perfil.equals("Usuário")){
            txtIdUsuario.setText("" + id);
            txtSenhaUsuario.setEditable(false);
            pesquisarUsuario();
            txtIdUsuario.setEnabled(false);
            btnPesquisarUsuario.setVisible(false);
            cboPerfilUsuario.setVisible(false);
            btnAdicionarUsuario.setVisible(false);
            btnExcluirUsuario.setVisible(false);        
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdUsuario = new javax.swing.JTextField();
        txtNomeExibicao = new javax.swing.JTextField();
        txtLoginUsuario = new javax.swing.JTextField();
        txtSenhaUsuario = new javax.swing.JPasswordField();
        cboPerfilUsuario = new javax.swing.JComboBox<>();
        chkSenha = new javax.swing.JCheckBox();
        btnAlterarUsuario = new javax.swing.JButton();
        btnAdicionarUsuario = new javax.swing.JButton();
        btnExcluirUsuario = new javax.swing.JButton();
        btnPesquisarUsuario = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        txtIdUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));
        txtIdUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdUsuarioActionPerformed(evt);
            }
        });

        txtNomeExibicao.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome de Exibição"));
        txtNomeExibicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeExibicaoActionPerformed(evt);
            }
        });

        txtLoginUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Login"));
        txtLoginUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginUsuarioActionPerformed(evt);
            }
        });

        txtSenhaUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Senha"));

        cboPerfilUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuário", "Admin" }));

        chkSenha.setText("Alterar Senha");
        chkSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSenhaActionPerformed(evt);
            }
        });

        btnAlterarUsuario.setBackground(new java.awt.Color(0, 106, 67));
        btnAlterarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterarUsuario.setText("Alterar");
        btnAlterarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarUsuarioActionPerformed(evt);
            }
        });

        btnAdicionarUsuario.setBackground(new java.awt.Color(0, 106, 67));
        btnAdicionarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnAdicionarUsuario.setText("Adicionar");
        btnAdicionarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdicionarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarUsuarioActionPerformed(evt);
            }
        });

        btnExcluirUsuario.setBackground(new java.awt.Color(0, 106, 67));
        btnExcluirUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirUsuario.setText("Excluir");
        btnExcluirUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirUsuarioActionPerformed(evt);
            }
        });

        btnPesquisarUsuario.setBackground(new java.awt.Color(0, 106, 67));
        btnPesquisarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisarUsuario.setText("Pesquisar");
        btnPesquisarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarUsuarioActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\é o r's\\Desktop\\leftarrow1_80827.png")); // NOI18N
        jButton5.setToolTipText("Voltar");
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtSenhaUsuario)
                                .addComponent(txtLoginUsuario)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(cboPerfilUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chkSenha))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnPesquisarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnAlterarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNomeExibicao, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdicionarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnExcluirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeExibicao, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLoginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboPerfilUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkSenha))
                .addGap(18, 18, 18)
                .addComponent(btnAlterarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeExibicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeExibicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeExibicaoActionPerformed

    private void txtLoginUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginUsuarioActionPerformed

    private void txtIdUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdUsuarioActionPerformed

    private void chkSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSenhaActionPerformed
        // TODO add your handling code here:
        txtSenhaUsuario.setText(null);
        txtSenhaUsuario.requestFocus();
	txtSenhaUsuario.setEditable(true);
        txtSenhaUsuario.setEnabled(true);
    }//GEN-LAST:event_chkSenhaActionPerformed

    private void btnAlterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarUsuarioActionPerformed
        // TODO add your handling code here:
         if (chkSenha.isSelected()) {
        	alterarUsuarioSenha();
	} else {
		alterarUsuario();
	}
    }//GEN-LAST:event_btnAlterarUsuarioActionPerformed

    private void btnPesquisarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarUsuarioActionPerformed
        // TODO add your handling code here:
         pesquisarUsuario();
    }//GEN-LAST:event_btnPesquisarUsuarioActionPerformed

    private void btnAdicionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarUsuarioActionPerformed
        // TODO add your handling code here:
         adicionarUsuario();
    }//GEN-LAST:event_btnAdicionarUsuarioActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirUsuarioActionPerformed
        // TODO add your handling code here:
        excluirUsuario();

    }//GEN-LAST:event_btnExcluirUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfiguracoesTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfiguracoesTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfiguracoesTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfiguracoesTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfiguracoesTela(perfil, id).setVisible(true);
            }
        });
    }
    
     ConnectionFactory cf = new ConnectionFactory();
    
   
    
      private void pesquisarUsuario() {
		if (txtIdUsuario.getText().isEmpty()) {
			JOptionPane.showMessageDialog(null, "Digite o id da lixeira");
			txtIdUsuario.requestFocus();
		} else {
			String read = "select * from tb_usuario where id = ?";
			try {
				Connection con = cf.conectar();
				PreparedStatement pst = con.prepareStatement(read);
				pst.setString(1, txtIdUsuario.getText());
				ResultSet rs = pst.executeQuery();
				if (rs.next()) {				
                                        txtNomeExibicao.setText(rs.getString("nomeExibicao")); 
                                        txtLoginUsuario.setText(rs.getString("login"));
                                        txtSenhaUsuario.setText(rs.getString("senha"));
                                        cboPerfilUsuario.setSelectedItem(rs.getString("perfil"));
				} else {
					JOptionPane.showMessageDialog(null, "Usuario não cadastrado");                                                                            
				}
				con.close();
			} catch (Exception e) {
				System.out.println(e);
			}
		}
	}
      
      
      private void adicionarUsuario() {

                String Senha = new String(txtSenhaUsuario.getPassword());
        
		if (txtNomeExibicao.getText().isEmpty()) {
			JOptionPane.showMessageDialog(null, "Informe o nome de exibição!");
			txtNomeExibicao.requestFocus();
		}else if (txtLoginUsuario.getText().isEmpty()) {
			JOptionPane.showMessageDialog(null, "Informe o login do usuario");
			txtLoginUsuario.requestFocus();
		}else if (txtSenhaUsuario.getText().isEmpty()) {
			JOptionPane.showMessageDialog(null, "Informe a senha do usuario");
			txtSenhaUsuario.requestFocus();
                }else if (cboPerfilUsuario.getSelectedItem().equals("")) {
			JOptionPane.showMessageDialog(null, "Informe o perfil do usuario");
			cboPerfilUsuario.requestFocus();
		}else{
			String create = "insert into tb_usuario(nomeExibicao, login, senha, perfil) values (?,?,md5(?),?)";
			try {
				Connection con = cf.conectar();
				PreparedStatement pst = con.prepareStatement(create);
				pst.setString(1, txtNomeExibicao.getText());
				pst.setString(2, txtLoginUsuario.getText());
				pst.setString(3, Senha);
                                pst.setString(4, cboPerfilUsuario.getSelectedItem().toString());
				pst.executeUpdate();
				JOptionPane.showMessageDialog(null, "Usuario Cadastrado!");
                                this.dispose();
                                limparCampos();
                                txtIdUsuario.setText(null);                   
				con.close(); 
			}catch (SQLIntegrityConstraintViolationException ex) {
				JOptionPane.showMessageDialog(null, "Login em uso.\nEscolha outro login.");
				txtLoginUsuario.setText(null);
				txtLoginUsuario.requestFocus();
                        }catch (Exception e) {
				e.printStackTrace();
			}
		}
	}
      
      private void alterarUsuario() {
		if (txtNomeExibicao.getText().isEmpty()) {
			JOptionPane.showMessageDialog(null, "Preencha o nome de exibição");
			txtNomeExibicao.requestFocus();
		} else if (txtLoginUsuario.getText().isEmpty()) {
			JOptionPane.showMessageDialog(null, "Preencha o Login");
			txtLoginUsuario.requestFocus();
		} else if (txtSenhaUsuario.getText().isEmpty()) {
			JOptionPane.showMessageDialog(null, "Digite a senha do usuario");
			txtSenhaUsuario.requestFocus();
		} else if (cboPerfilUsuario.getSelectedItem().equals("")) {
			JOptionPane.showMessageDialog(null, "Digite o perfil");
			cboPerfilUsuario.requestFocus();
		} else {
			String update = "update tb_usuario set nomeExibicao=?, login=?, perfil=? where id=?";
			try {
				Connection con = cf.conectar();
				PreparedStatement pst = con.prepareStatement(update);
				pst.setString(1, txtNomeExibicao.getText());
				pst.setString(2, txtLoginUsuario.getText());
				pst.setString(3, cboPerfilUsuario.getSelectedItem().toString());
				pst.setString(4, txtIdUsuario.getText());
				pst.executeUpdate();
				JOptionPane.showMessageDialog(null, "Usuário alterado com Sucesso!");
				con.close();
                        }catch (SQLIntegrityConstraintViolationException ex) {
				JOptionPane.showMessageDialog(null, "Login em uso.\nEscolha outro login.");
				txtLoginUsuario.setText(null);
				txtLoginUsuario.requestFocus();
			} catch (Exception e) {
				System.out.println(e);
			}

		}

	}
      
      private void alterarUsuarioSenha() {
          
                String capturarSenha = new String(txtSenhaUsuario.getPassword());
		
		if (txtNomeExibicao.getText().isEmpty()) {
			JOptionPane.showMessageDialog(null, "Preencha o nome de exibição");
			txtNomeExibicao.requestFocus();
		} else if (txtLoginUsuario.getText().isEmpty()) {
			JOptionPane.showMessageDialog(null, "Preencha o Login");
			txtLoginUsuario.requestFocus();
		} else if (txtSenhaUsuario.getText().isEmpty()) {
			JOptionPane.showMessageDialog(null, "Digite a senha do usuario");
			txtSenhaUsuario.requestFocus();
		} else if (cboPerfilUsuario.getSelectedItem().equals("")) {
			JOptionPane.showMessageDialog(null, "Digite o perfil");
			cboPerfilUsuario.requestFocus();
		} else {
			String update = "update tb_usuario set nomeExibicao=?, login=?, senha=md5(?), perfil=? where id=?";
			try {
				Connection con = cf.conectar();
				PreparedStatement pst = con.prepareStatement(update);
				// Substituir os ???? pelo conteúdo das caixas de texto
				pst.setString(1, txtNomeExibicao.getText());
				pst.setString(2, txtLoginUsuario.getText());
                                pst.setString(3, capturarSenha);
				pst.setString(4, cboPerfilUsuario.getSelectedItem().toString());
				pst.setString(5, txtIdUsuario.getText());
				pst.executeUpdate();
				JOptionPane.showMessageDialog(null, "Usuário alterado com Sucesso!");
                                txtSenhaUsuario.setEditable(false);
                                chkSenha.setSelected(false);
				con.close();
                        }catch (SQLIntegrityConstraintViolationException ex) {
				JOptionPane.showMessageDialog(null, "Login em uso.\nEscolha outro login.");
				txtLoginUsuario.setText(null);
				txtLoginUsuario.requestFocus();
			} catch (Exception e) {
				System.out.println(e);
			}
		}
	}
    
       private void excluirUsuario() {
        if (txtIdUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o Id do usuário");
            txtIdUsuario.requestFocus();
        } else{
                int confirma = JOptionPane.showConfirmDialog(null, "Confirma a exclusão do usuário?", "Atenção!", JOptionPane.YES_NO_OPTION);
                if (confirma == JOptionPane.YES_OPTION) {
                        String delete = "delete from tb_usuario where id=?";
                try {
                    Connection con = cf.conectar();
                    PreparedStatement pst = con.prepareStatement(delete);
                    pst.setString(1, txtIdUsuario.getText());
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Usuário excluído com sucesso");
                    limparCampos();
                    txtIdUsuario.setText(null);
                    con.close();
                } catch (Exception e) {
                    System.out.println(e);
               }
             }
          }
       }
        
        public void limparCampos(){
            chkSenha.setSelected(false);
            txtNomeExibicao.setText(null);
            txtLoginUsuario.setText(null);
            txtSenhaUsuario.setText(null);
            cboPerfilUsuario.setSelectedItem("Usuário");
        }
  
           
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarUsuario;
    private javax.swing.JButton btnAlterarUsuario;
    private javax.swing.JButton btnExcluirUsuario;
    private javax.swing.JButton btnPesquisarUsuario;
    public static javax.swing.JComboBox<String> cboPerfilUsuario;
    private javax.swing.JCheckBox chkSenha;
    private javax.swing.JButton jButton5;
    private javax.swing.JTextField txtIdUsuario;
    private javax.swing.JTextField txtLoginUsuario;
    private javax.swing.JTextField txtNomeExibicao;
    private javax.swing.JPasswordField txtSenhaUsuario;
    // End of variables declaration//GEN-END:variables
}
