/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Telas;

import Classes.Lixeira;
import Classes.LixeiraDAO;
import Classes.Segundos;
import Classes.Lixo;
import Classes.LixoDAO;
import Classes.UsuarioDAO;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author é o r's
 */
public class Jogo extends javax.swing.JFrame {
    
    LixoDAO td = new LixoDAO();
    LixeiraDAO bd = new LixeiraDAO();
    ArrayList<Lixo> trashlist = new ArrayList<>();
    ArrayList<Lixeira> binlist = new ArrayList<>();
    Segundos seconds;
    Thread tSec;
    private Lixo lixoEscolhido1;
    private Lixo lixoEscolhido2;
    private Lixo lixoEscolhido3;
    private Lixeira lixeira;
    static String login, nomeExib;
    static int scoreArmazenado,id;
        
    int score = 0;    
    
    /**
     * Creates new form ProjectExec
     */
    public Jogo(String login, String nomeExib, int score, int id) {
        super("RECYCLE RUSH");
        initComponents();
        this.setLocationRelativeTo(null);
        this.login = login;
        this.nomeExib = nomeExib;
        this.scoreArmazenado = score;  
        this.id = id;
        
        seconds = new Segundos();
        tSec = new Thread(seconds); 
        tSec.start();
        
        trashlist = td.listar();
        binlist = bd.listar();
        iniciarJogo();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSeconds = new javax.swing.JLabel();
        lixeiraJogo = new javax.swing.JLabel();
        lixo1 = new javax.swing.JButton();
        lixo2 = new javax.swing.JButton();
        lixo3 = new javax.swing.JButton();
        lblScore = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Time:");

        txtSeconds.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtSeconds.setText("0");

        lixeiraJogo.setPreferredSize(new java.awt.Dimension(120, 120));

        lixo1.setText("jButton2");
        lixo1.setBorderPainted(false);
        lixo1.setContentAreaFilled(false);
        lixo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lixo1.setPreferredSize(new java.awt.Dimension(64, 58));
        lixo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lixo1ActionPerformed(evt);
            }
        });

        lixo2.setText("jButton1");
        lixo2.setBorderPainted(false);
        lixo2.setContentAreaFilled(false);
        lixo2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lixo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lixo2ActionPerformed(evt);
            }
        });

        lixo3.setText("jButton2");
        lixo3.setBorderPainted(false);
        lixo3.setContentAreaFilled(false);
        lixo3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lixo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lixo3ActionPerformed(evt);
            }
        });

        lblScore.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblScore.setText("0");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Score:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblScore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtSeconds)
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lixeiraJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lixo1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(lixo2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addComponent(lixo3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSeconds)
                    .addComponent(lblScore)
                    .addComponent(jLabel2))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lixo1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lixo2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lixo3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(lixeiraJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void lixo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lixo1ActionPerformed
        // TODO add your handling code here:              
        if(lixoEscolhido1.getTipoLixo().equals(lixeira.getTipoLixeira())) {
            txtSeconds.setText("0");
            score = score + 1;
            String scoreString = Integer.toString(score);
            lblScore.setText(scoreString);
            iniciarJogo();
        } else {
            seconds.stop = true;
            this.dispose();
            GameOver go = new GameOver(login, nomeExib, score, id);
            go.setVisible(true);
            UsuarioDAO ud = new UsuarioDAO();
            ud.atualizarScore(scoreArmazenado, id);
        }
    }//GEN-LAST:event_lixo1ActionPerformed

    private void lixo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lixo2ActionPerformed
        // TODO add your handling code here:
        if(lixoEscolhido2.getTipoLixo().equals(lixeira.getTipoLixeira())) {
            txtSeconds.setText("0");
            score = score + 1;
            String scoreString = Integer.toString(score);
            lblScore.setText(scoreString);  
            iniciarJogo();
        } else {
            seconds.stop = true;
            this.dispose();
            GameOver go = new GameOver(login, nomeExib, score, id);
            go.setVisible(true);
            UsuarioDAO ud = new UsuarioDAO();
            ud.atualizarScore(scoreArmazenado, id);
        }
    }//GEN-LAST:event_lixo2ActionPerformed

    private void lixo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lixo3ActionPerformed
        // TODO add your handling code here:
        if(lixoEscolhido3.getTipoLixo().equals(lixeira.getTipoLixeira())) {
            txtSeconds.setText("0");
            score = score + 1;
            String scoreString = Integer.toString(score);
            lblScore.setText(scoreString);   
            iniciarJogo();
        } else {
            seconds.stop = true;
            this.dispose();
            GameOver go = new GameOver(login, nomeExib, score, id);
            go.setVisible(true);
            UsuarioDAO ud = new UsuarioDAO();
            ud.atualizarScore(scoreArmazenado, id);
        }
    }//GEN-LAST:event_lixo3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogo(login, nomeExib, scoreArmazenado, id).setVisible(true);
            }
        });
    }
    
    private void iniciarJogo(){
        Random rgd = new Random();  

        if(trashlist.size() > 0 && binlist.size() > 0){
            int lixoGerado1 = rgd.nextInt(trashlist.size());
            int lixoGerado2 = rgd.nextInt(trashlist.size());
            int lixoGerado3 = rgd.nextInt(trashlist.size());
            int lixeira1 = rgd.nextInt(binlist.size());

            while (lixoGerado2 == lixoGerado1 || trashlist.get(lixoGerado2).getTipoLixo().equals(trashlist.get(lixoGerado1).getTipoLixo())) {
                lixoGerado2 = rgd.nextInt(trashlist.size());
            }

            while (lixoGerado3 == lixoGerado1 || lixoGerado3 == lixoGerado2 ||
                   trashlist.get(lixoGerado3).getTipoLixo().equals(trashlist.get(lixoGerado1).getTipoLixo()) ||
                   trashlist.get(lixoGerado3).getTipoLixo().equals(trashlist.get(lixoGerado2).getTipoLixo())) {
                lixoGerado3 = rgd.nextInt(trashlist.size());
            }

            lixoEscolhido1 = trashlist.get(lixoGerado1);
            lixoEscolhido2 = trashlist.get(lixoGerado2);
            lixoEscolhido3 = trashlist.get(lixoGerado3);


            boolean lixeiraCorrespondente = false;
            while (!lixeiraCorrespondente) {
                lixeira1 = rgd.nextInt(binlist.size());
                lixeira = binlist.get(lixeira1);

                if (lixeira.getTipoLixeira().equals(lixoEscolhido1.getTipoLixo()) ||
                    lixeira.getTipoLixeira().equals(lixoEscolhido2.getTipoLixo()) ||
                    lixeira.getTipoLixeira().equals(lixoEscolhido3.getTipoLixo())) {
                    lixeiraCorrespondente = true;
                }
            }                  

            PuxarImagemLixo(lixoEscolhido1, lixo1);
            
            PuxarImagemLixo(lixoEscolhido2, lixo2);
            
            PuxarImagemLixo(lixoEscolhido3, lixo3);

            PuxarImagemLixeira(lixeira, lixeiraJogo);                
        } else {
            System.out.println("Cadastre mais lixos e/ou Lixeiras");
        }
    }
    
    public void PuxarImagemLixo(Lixo lixo,JButton btn){
        String pathIcon = lixo.getCaminhoImg();
        File icon = new File(pathIcon);
        Image foto;
        try{
            foto = ImageIO.read(icon).getScaledInstance(btn.getWidth(), btn.getHeight(),Image.SCALE_SMOOTH);
            btn.setIcon(new ImageIcon(foto));
            btn.updateUI();
        } catch (IOException ex) {
            Logger.getLogger(Jogo.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }    
    
    public void PuxarImagemLixeira(Lixeira lixeira,JLabel lbl){
        String pathIcon = lixeira.getCaminhoImg();
        File icon = new File(pathIcon);
        Image foto;
        try{
            foto = ImageIO.read(icon).getScaledInstance(lbl.getWidth(), lbl.getHeight(),Image.SCALE_SMOOTH);
            lbl.setIcon(new ImageIcon(foto));
            lbl.updateUI();
        } catch (IOException ex) {
            Logger.getLogger(Jogo.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }   
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel lblScore;
    private javax.swing.JLabel lixeiraJogo;
    private javax.swing.JButton lixo1;
    private javax.swing.JButton lixo2;
    private javax.swing.JButton lixo3;
    public static javax.swing.JLabel txtSeconds;
    // End of variables declaration//GEN-END:variables
}
